PollPulse/PollPulse/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('poll.urls')),
]

PollPulse/poll/urls.py
from django.urls import path
from . import views
from .views import activate_account

app_name = 'poll'

urlpatterns = [

    path('', views.home, name="home"),  # Root URL mapped to home view
    path('register/', views.register, name='register'),  # User registration
    path('login/', views.user_login, name='login'),  # User login
    path('logout/', views.user_logout, name="logout"),  # User logout
    path('polls/create/', views.create_poll, name='create_poll'),  # Create a poll
    path('dashboard/', views.dashboard, name='dashboard'),  # User dashboard
    path('participate/', views.participate_view, name='participate_poll'),  # Participate in a poll
    # path('manageFriends/', views.manage_friends, name='manage_friends'),  # Uncomment if manage friends feature is used
    path('feedback/', views.feedback, name='feedback'),  # Feedback view
    path('activate/<uidb64>/<token>/', activate_account, name='activate_account'),  # Account activation link

    path('', views.home, name="home"),  # This maps the root URL to the home view
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/',views.user_logout,name="logout"),
    path('polls/create/', views.create_poll, name='create_poll'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('participate/', views.participate_view, name='participate_poll'),
    # path('manageFriends/', views.manage_friends, name='manage_friends'),
    path('feedback/', views.feedback, name= 'feedback'),
    path('activate/<uidb64>/<token>/', views.activate_account, name='activate_account'),


    # Poll-specific URLs
    path('<int:poll_id>/', views.detail, name='detail'),  # Poll details
    path('<int:poll_id>/vote/', views.vote, name='vote'),  # Vote in a poll
    path('<int:poll_id>/results/', views.results, name='results'),  # View poll results
    path('<int:poll_id>/report/', views.report_poll, name='report_poll'),  # Report a poll
    path('comments/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    
    # Uncomment if using CAPTCHA
    # path('captcha/', include('captcha.urls')),  # Add captcha functionality if needed

    # Add other paths as needed in the future
]

PollPulse/poll/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.crypto import get_random_string
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
import hashlib
import os
from .utils import validate_poll_question

class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    end_date = models.DateTimeField('date ended', null=True, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='polls')
    is_multiple_choice = models.BooleanField(default=False)
    choices_hash = models.CharField(max_length=64, editable=False, blank=True)

    def generate_choices_hash(self):
        if not self.pk:
            return ''
        # Get all the choices related to this poll and sort them
        choices = self.choices.all().values_list('choice_text', flat=True)
        # Convert choices list to a sorted string
        choices_string = ''.join(sorted(choices))
        # Generate the hash
        return hashlib.sha256(choices_string.encode('utf-8')).hexdigest()

    def save(self, *args, **kwargs):
        # Ensure the choices hash is generated before saving the poll
        super().save(*args, **kwargs)
        self.choices_hash = self.generate_choices_hash()
        super().save(update_fields=['choices_hash'])

    def __str__(self):
        return self.question

    def is_active(self):
        # Check if poll is still active
        if self.end_date:
            return timezone.now() < self.end_date
        return True

    def clean(self):
        # Validate poll question against inappropriate language
        if not validate_poll_question(self.question):
            raise ValidationError("Poll question contains inappropriate language.")

    @staticmethod
    def load_cuss_words():
        """
        Loads the list of cuss words from the cuss_words.txt file and returns it as a list.
        """
        file_path = os.path.join(os.path.dirname(__file__), 'data', 'cuss_words.txt')
        with open(file_path, 'r') as file:
            cuss_words = file.read().splitlines()  # Read all lines into a list
        return cuss_words


class Choice(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE, related_name='choices')
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Report(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    reason = models.CharField(max_length=100)
    details = models.TextField(blank=True)

    def __str__(self):
        return f"Report for Poll {self.poll.id} by User {self.user.id}"


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'choice')


class Comment(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE, related_name='comments')
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment by {self.user.username} on Poll {self.poll.id}"


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_verified = models.BooleanField(default=False)
    verification_token = models.CharField(max_length=64, blank=True)
    uidb64 = models.CharField(max_length=64, blank=True)

    def __str__(self):
        return f"{self.user.username} Profile"

    def save(self, *args, **kwargs):
        # Generate a verification token and uidb64 if not already set
        if not self.verification_token:
            self.verification_token = get_random_string(64)
        if not self.uidb64:
            self.uidb64 = urlsafe_base64_encode(force_bytes(self.user.pk))
        super().save(*args, **kwargs)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

PollPulse/poll/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.encoding import force_str, force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.conf import settings
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.urls import reverse
from .models import Poll, Choice, Vote, Comment
from .forms import CreateUserForm, LoginForm, PollForm, ChoiceForm, ReportForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout as auth_logout
from django.forms import modelformset_factory
from django.utils import timezone
from django.contrib import messages
from .utils import create_user, validate_poll_question, send_verification_email
from django.db import transaction
from .forms import CommentForm



from django.conf import settings
import logging

def home(request):
    return render(request, 'poll/home.html')

def register(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False  # Deactivate account until email verification
            user.save()

            send_verification_email(user)
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account was created for {username}. Please check your email to verify your account.')
            return redirect('poll:login')
        else:
            messages.error(request, 'Please correct the errors below.')


            print(form.errors)
            for field, errors in form.errors.items():
                for error in errors:
                    print(f"Error in {field}: {error}")

    context = {'registerform': form}
    return render(request, 'poll/register.html', context=context)

def user_login(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                if hasattr(user, 'profile') and user.profile.email_verified:
                    login(request, user)
                    return redirect('poll:dashboard')
                else:
                    messages.error(request, 'Please verify your email address before logging in.')
            else:
                messages.error(request, 'Invalid username or password.')
    context = {'loginform': form}
    return render(request, 'poll/login.html', context=context)

@login_required
def dashboard(request):
    return render(request, 'poll/dashboard.html')

@login_required
def create_poll(request):
    ChoiceFormSet = modelformset_factory(Choice, form=ChoiceForm, extra=2)

    if request.method == 'POST':
        poll_form = PollForm(request.POST)
        formset = ChoiceFormSet(request.POST, queryset=Choice.objects.none())
        
        if poll_form.is_valid() and formset.is_valid():
            poll = poll_form.save(commit=False)
            poll.created_by = request.user
            poll.pub_date = timezone.now()
            poll.save()  # Save poll first
            
            # Ensure the poll has a primary key
            if not poll.id:
                messages.error(request, 'The poll could not be saved.')
                return render(request, 'poll/create_poll.html', {'poll_form': poll_form, 'formset': formset})
            
            # Save choices
            for form in formset.cleaned_data:
                if form:
                    choice_text = form['choice_text']
                    try:
                        Choice.objects.create(poll=poll, choice_text=choice_text, votes=0)
                    except Exception as e:
                        print(f"Error saving choice '{choice_text}': {e}")
                        messages.error(request, 'There was an error saving the poll choices.')
                        return render(request, 'poll/create_poll.html', {'poll_form': poll_form, 'formset': formset})

            return redirect('poll:dashboard')
        else:
            print(f"Poll form errors: {poll_form.errors}")
            print(f"Formset errors: {formset.errors}")
            messages.error(request, 'There were errors in the form.')
    else:
        poll_form = PollForm()
        formset = ChoiceFormSet(queryset=Choice.objects.none())

    return render(request, 'poll/create_poll.html', {'poll_form': poll_form, 'formset': formset})


@login_required
def user_logout(request):
    auth_logout(request)
    return redirect('poll:home')

@login_required
def feedback(request):
    user_polls = Poll.objects.filter(created_by=request.user).order_by('-pub_date')
    
    polls_with_choices_and_comments = []
    for poll in user_polls:
        choices = poll.choices.all()
        comments = poll.comments.all()  # Fetch comments related to the poll
        poll_data = {
            'poll': poll,
            'choices': choices,
            'comments': comments
        }
        polls_with_choices_and_comments.append(poll_data)
    
    return render(request, 'poll/feedback.html', {'polls_with_choices': polls_with_choices_and_comments})


def detail(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)

    if request.method == 'POST' and 'comment' in request.POST:
        comment_text = request.POST['comment']
        if request.user.is_authenticated and comment_text:
            Comment.objects.create(poll=poll, user=request.user, comment_text=comment_text)
            return redirect('poll:detail', poll_id=poll.id)

    comments = Comment.objects.filter(poll=poll) if request.user == poll.created_by else Comment.objects.filter(poll=poll, user=request.user)

    return render(request, 'poll/detail.html', {
        'poll': poll,
        'comments': comments
    })

@login_required
def vote(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    if not poll.is_active():
        return render(request, 'poll/detail.html', {'poll': poll, 'error_message': "Poll is closed."})

    if poll.is_multiple_choice:
        selected_choices = request.POST.getlist('choices')
        if not selected_choices:
            return render(request, 'poll/detail.html', {'poll': poll, 'error_message': "You didn't select any choice."})

        if Vote.objects.filter(user=request.user, choice__poll=poll).exists():
            return render(request, 'poll/detail.html', {'poll': poll, 'error_message': "You have already voted."})

        for choice_id in selected_choices:
            try:
                selected_choice = poll.choices.get(pk=choice_id)
                selected_choice.votes += 1
                selected_choice.save()
                Vote.objects.create(user=request.user, choice=selected_choice)
            except Choice.DoesNotExist:
                return render(request, 'poll/detail.html', {'poll': poll, 'error_message': "Invalid choice."})
    else:
        try:
            selected_choice = poll.choices.get(pk=request.POST['choice'])
            if Vote.objects.filter(user=request.user, choice=selected_choice).exists():
                return render(request, 'poll/detail.html', {'poll': poll, 'error_message': "You have already voted."})
            selected_choice.votes += 1
            selected_choice.save()
            Vote.objects.create(user=request.user, choice=selected_choice)
        except (KeyError, Choice.DoesNotExist):
            return render(request, 'poll/detail.html', {'poll': poll, 'error_message': "You didn't select a choice."})

    return HttpResponseRedirect(reverse('poll:results', args=(poll.id,)))

def results(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)

    # Calculate total votes
    total_votes = float(sum(choice.votes for choice in poll.choices.all()))
    
    # Calculate choices with their percentage
    choices_with_percentage = [
        {
            'choice_text': choice.choice_text,
            'votes': choice.votes,
            'percentage': (choice.votes / total_votes) * 100 if total_votes > 0 else 0
        }
        for choice in poll.choices.all()
    ]
    
    # Handle comment form submission
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.poll = poll
            comment.user = request.user
            comment.save()
            return redirect('poll:results', poll_id=poll_id)
    else:
        comment_form = CommentForm()

    # Get comments for the poll
    comments = poll.comments.all()
    
    # Check if the current user is the creator of the poll
    is_creator = request.user == poll.created_by

    # Prepare context
    context = {
        'poll': poll,
        'total_votes': total_votes,
        'choices': choices_with_percentage,
        'comment_form': comment_form,
        'comments': comments,
        'is_creator': is_creator,
    }
    
    return render(request, 'poll/results.html', context)
@login_required
def participate_view(request):
    polls = Poll.objects.all().order_by('-pub_date')
    user_votes = Vote.objects.filter(user=request.user).values_list('choice__poll', flat=True)
    for poll in polls:
        poll.has_voted = poll.id in user_votes


PollPulse/poll/templates/poll/activate_account_email.html
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>{% trans "Activate your account" %}</title>
</head>
<body>
    <p>Hello {{ user.username }},</p>
    <p>Thank you for registering. Please click the link below to activate your account:</p>
    <p><a href="{{ domain }}{% url 'poll:activate_account' uidb64=uid token=token %}">Activate your account</a></p>
    <p>If you did not register for an account, please ignore this email.</p>
    <p>Thanks!</p>
</body>
</html>

PollPulse/poll/templates/poll/create_poll.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Poll - Poll Pulse</title>
    <link rel="stylesheet" href="{% static 'poll/style1.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200..1000&display=swap" rel="stylesheet">
</head>
<body>
    <nav>
        <div class="logo">
            <h1>PollPulse</h1>
        </div>
        <ul class="nav-links">
            <li><a href="{% url 'poll:home' %}">Home</a></li>
            <li><a href="{% url 'poll:dashboard' %}">Dashboard</a></li>
            
            <li><a href="{% url 'poll:feedback' %}">Feedback</a></li>
            <li><a href="{% url 'poll:participate_poll' %}">Participate in Poll</a></li>
        </ul>
    </nav>
    
    <main>
        <section class="create-poll">
            <h2>Create a New Poll</h2>
            <form method="post" id="pollForm">
                {% csrf_token %}
                {{ poll_form.as_p }}

                <h3>Choices</h3>
                {{ formset.management_form }}
                <div id="formset-area">
                    {% for form in formset %}
                        <div class="choice" data-form-index="{{ forloop.counter0 }}">
                            {{ form.choice_text.label_tag }}
                            {{ form.choice_text }}
                            <button type="button" class="remove-choice" onclick="removeChoice(this)">Remove</button>
                        </div>
                    {% endfor %}
                </div>
                <button type="button" id="add-choice">Add more choices</button>
                <button type="submit">Create Poll</button>
            </form>
        </section>
    </main>

    <script>
        document.getElementById('add-choice').addEventListener('click', function() {
            var formsetArea = document.getElementById('formset-area');
            var formCount = formsetArea.children.length;
            var totalForms = document.getElementById('id_form-TOTAL_FORMS');
            var formIndex = parseInt(totalForms.value);

            var newForm = formsetArea.children[0].cloneNode(true); // Clone the first form
            var inputs = newForm.querySelectorAll('input');
            
            inputs.forEach(function(input) {
                var newName = input.name.replace(/-(\d+)-/, '-' + formIndex + '-');
                var newId = input.id.replace(/-(\d+)-/, '-' + formIndex + '-');
                input.name = newName;
                input.id = newId;
                input.value = '';
            });

            newForm.querySelector('.remove-choice').style.display = 'inline-block'; // Show the remove button for new choice
            formsetArea.appendChild(newForm);

            totalForms.value = formIndex + 1;
        });

        function removeChoice(button) {
            var formsetArea = document.getElementById('formset-area');
            var formIndex = button.parentElement.getAttribute('data-form-index');
            button.parentElement.remove();
            
            var totalForms = document.getElementById('id_form-TOTAL_FORMS');
            var newTotal = parseInt(totalForms.value) - 1;
            totalForms.value = newTotal;
            
            // Update form indices
            formsetArea.querySelectorAll('.choice').forEach(function(div, index) {
                div.setAttribute('data-form-index', index);
                var inputs = div.querySelectorAll('input');
                inputs.forEach(function(input) {
                    input.name = input.name.replace(/-(\d+)-/, '-' + index + '-');
                    input.id = input.id.replace(/-(\d+)-/, '-' + index + '-');
                });
            });
        }
    </script>
</body>
</html>


PollPulse/poll/templates/poll/dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PollPulse Dashboard</title>

    <link rel="stylesheet" href="../../static/poll/dashboard.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200..1000&display=swap" rel="stylesheet">
</head>

<body>
    <nav class="navbar">
        <div class="logo">
            <h1>PollPulse</h1>
        </div>
        <div class="dropdown">
            <button class="dropbtn" onclick="toggleDropdown()">
                {% if user.is_authenticated %}
                {{ user.username }}
                {% else %}
                Account
                {% endif %}
                <i class="arrow down"></i>
            </button>
            <div id="dropdownContent" class="dropdown-content">
                {% if user.is_authenticated %}
                <p>Name: {{ user.username }}</p>
                <p>Email: {{ user.email }}</p>
                <p>User ID: {{ user.id }}</p>
                {% else %}
                <p>Please login</p>
                {% endif %}
                <a href="{% url 'poll:logout' %}">Logout</a>
            </div>
        </div>
        {% if user.is_authenticated %}
        <a class="logout-button" href="{% url 'poll:logout' %}">Logout</a>
        {% endif %}
    </nav>
    <main class="dashboard">
        <div class="block" onclick="location.href='{% url 'poll:create_poll' %}'">
            <i class="fa fa-plus-circle"></i>
            <p>Create Poll</p>
        </div>
        {% comment %} <div class="block" onclick="location.href='{% url 'poll:manage_friends' %}'">
            <i class="fa fa-users"></i>
            <p>Manage Friends</p>
        </div> {% endcomment %}
        <div class="block" onclick="location.href='{% url 'poll:feedback' %}'">
            <i class="fa fa-comments"></i>
            <p>View Feedback</p>
        </div>
        <div class="block" onclick="location.href='{% url 'poll:participate_poll' %}'">
            <i class="fa fa-check-circle"></i>
            <p>Participate in Poll</p>
        </div>
    </main>
    <script>
        function toggleDropdown() {
            var dropdownContent = document.getElementById("dropdownContent");
            dropdownContent.classList.toggle("show");
        }


        window.onclick = function (event) {
            if (!event.target.matches('.dropbtn')) {
                var dropdowns = document.getElementsByClassName("dropdown-content");
                for (var i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.classList.contains('show')) {
                        openDropdown.classList.remove('show');
                    }
                }
            }
        }
    </script>
</body>

</html>

PollPulse/poll/templates/poll/feedback.html
{% load static %}
{% load tz %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Feedback - Poll Pulse</title>
    <link rel="stylesheet" href="{% static 'poll/feedback.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;400;600;800&display=swap" rel="stylesheet">
</head>
<body>
    <!-- Navigation Bar -->
    <nav>
        <div class="logo">
            <h1>PollPulse</h1>
        </div>
        <ul class="nav-links">
            <li><a href="{% url 'poll:home' %}">Home</a></li>
            <li><a href="{% url 'poll:dashboard' %}">Dashboard</a></li>
            <li><a href="{% url 'poll:create_poll' %}">Create Poll</a></li>
            <li><a href="{% url 'poll:participate_poll' %}">Participate in Poll</a></li>
        </ul>
    </nav>

    <!-- Main Feedback Section -->
    <main>
        <section class="feedback">
            <h2>My Polls and Feedback</h2>

            <!-- Check if there are polls -->
            {% if polls_with_choices %}
                <ul class="poll-list">
                    <!-- Loop through each poll and its choices -->
                    {% for poll_data in polls_with_choices %}
                        <li class="poll-item">
                            <h3 class="poll-question">{{ poll_data.poll.question }}</h3>
                            <p class="poll-date">Published on: {{ poll_data.poll.pub_date|localtime|date:"F j, Y, g:i a" }}</p>
                            {% if poll_data.poll.end_date %}
                                <p class="poll-end-date">Ends on: {{ poll_data.poll.end_date }}</p>
                            {% endif %}
                            
                            <h4>Options and Votes:</h4>
                            <ul class="options-list">
                                {% for choice in poll_data.choices %}
                                    <li>{{ choice.choice_text }} - {{ choice.votes }} votes</li>
                                {% empty %}
                                    <li>No options yet.</li>
                                {% endfor %}
                            </ul>

                            <!-- Display Comments for each poll -->
                            <h4>Comments:</h4>
                            <ul class="comment-list">
                                {% for comment in poll_data.poll.comments.all %}
                                    <li>
                                        <strong class="comment-author">{{ comment.user }}</strong>: 
                                        <span class="comment-text">{{ comment.comment_text }}</span>
                                        <span class="comment-date">({{ comment.created_at|date:"F j, Y, g:i a" }})</span>
                                        {% if comment.user == request.user or poll_data.poll.created_by == request.user %}
                                            <a href="{% url 'poll:delete_comment' comment.id %}" class="delete-comment">Delete</a>
                                        {% endif %}
                                    </li>
                                {% empty %}
                                    <li>No comments yet.</li>
                                {% endfor %}
                            </ul>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>No polls found.</p>
            {% endif %}
        </section>
    </main>
</body>
</html>

PollPulse/poll/templates/poll/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PollPulse</title>
    <link rel="stylesheet" href="{% static 'poll/home.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;400;600;800&display=swap" rel="stylesheet">


    <head>

    <body>

        <nav>
            <div class="logo">
                <h1>PollPulse</h1>
            </div>
            <ul class="nav-links">
                <li><a href="#home">Home</a></li>
                <li><a href="{% url 'poll:register' %}">Register</a></li>
                <li><a href="{% url 'poll:login' %}">Login</a></li>
            </ul>
        </nav>


        <section id="home" class="welcome-section">
            <h2>Welcome to PollPulse</h2>
            <p>Your one-stop solution for creating and participating in polls.</p>
            <button onclick="document.getElementById('features').scrollIntoView({ behavior: 'smooth' });">Get
                Started</button>
        </section>


        <section id="features" class="features-section">
            {% comment %} <div class="feature-box">
                <h3>Manage Friends</h3>
                <p>Connect and manage your friends easily.</p>
            </div> {% endcomment %}
            <div class="feature-box">
                <h3>View Feedbacks</h3>
                <p>See what others are saying.</p>
            </div>
            <div class="feature-box">
                <h3>Create Poll</h3>
                <p>Create your own polls effortlessly.</p>
            </div>
            <div class="feature-box">
                <h3>Participate in Poll</h3>
                <p>Take part in polls and share your opinions.</p>
            </div>
        </section>

        <footer>
            <p>&copy; 2024 PollPulse. All rights reserved.</p>
        </footer>


    </body>

</html>